language: go

go:
  - "1.x"

script: ".scripts/build_crossplatform.sh $TRAVIS_TAG"

deploy:
  provider: releases
  api_key: "$GITHUB_OAUTH_TOKEN"
  file_glob: true
  file: dist/*
  skip_cleanup: true
  on:
    tags: true
